import type { Metadata } from 'next';
import AppLayout from '@/layouts/AppLayout';
import ToastLayout from '@/layouts/ToastLayout';
import ReduxProvider from '@/layouts/ReduxProvider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AppLayout>
            <ToastLayout>{children}</ToastLayout>
          </AppLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
